index:
    path: /
    controller: App\Controller\DefaultController::owlHomeDisplay

owlServicesDisplay:
    path: /owlServicesDisplay
    controller: App\Controller\DefaultController::owlServicesDisplay

owlReferencesDisplay:
    path: /owlReferencesDisplay
    controller: App\Controller\DefaultController::owlReferencesDisplay

owlContactDisplay:
    path: /owlContactDisplay
    controller: App\Controller\DefaultController::owlContactDisplay

owlBlogDisplay:
    path: /owlBlogDisplay
    controller: App\Controller\DefaultController::owlBlogDisplay

articleAdmin:
    path: /articleAdmin
    controller: App\Controller\ArticleController::articleAdminDisplay

article:
    path: /article
    controller: App\Controller\ArticleController::articleDisplay

addComment:
    path: /addComment
    controller: App\Controller\ArticleController::addComment


commentResponseUpdate:
    path: /commentResponseUpdate
    controller: App\Controller\ArticleController::commentResponseUpdate


commentResponseTrash:
    path: /commentResponseTrash
    controller: App\Controller\ArticleController::commentResponseTrash


commentUpdate:
    path: /commentUpdate
    controller: App\Controller\ArticleController::commentUpdate


commentTrash:
    path: /commentTrash
    controller: App\Controller\ArticleController::commentTrash

articleTrash:
    path: /articleTrash
    controller: App\Controller\ArticleController::articleTrash

articleUpdate:
    path: /articleUpdate
    controller: App\Controller\ArticleController::articleUpdate

articleFormDisplay:
    path: /articleFormDisplay
    controller: App\Controller\ArticleController::articleFormDisplay

commentVisibility:
    path: /commentVisibility
    controller: App\Controller\ArticleController::commentVisibility
