essai:
    path: /essai
    controller: App\Controller\DefaultController::essai

index:
    path: /
    controller: App\Controller\DefaultController::owlHomeDisplay

contactForm:
    path: /contactForm
    controller: App\Controller\DefaultController::contactForm

owlAgencyDisplay:
    path: /owlAgencyDisplay
    controller: App\Controller\DefaultController::owlAgencyDisplay

owlServicesDisplay:
    path: /owlServicesDisplay
    controller: App\Controller\DefaultController::owlServicesDisplay

owlReferencesDisplay:
    path: /owlReferencesDisplay
    controller: App\Controller\DefaultController::owlReferencesDisplay

owlContactDisplay:
    path: /owlContactDisplay
    controller: App\Controller\DefaultController::formContactDisplay

owlBlogDisplay:
    path: /owlBlogDisplay
    controller: App\Controller\DefaultController::owlBlogDisplay

adminArticle:
    path: /adminArticle
    controller: App\Controller\DefaultController::adminArticleDisplay

adminProspect:
    path: /adminProspect
    controller: App\Controller\DefaultController::adminProspectDisplay

nextActionSave:
    path: /nextActionSave
    controller: App\Controller\DefaultController::nextActionSave

lastActionSave:
    path: /lastActionSave
    controller: App\Controller\DefaultController::lastActionSave

article:
    path: /article
    controller: App\Controller\DefaultController::articleDisplay


articleTrash:
    path: /articleTrash
    controller: App\Controller\DefaultController::articleTrash

articleUpdate:
    path: /articleUpdate
    controller: App\Controller\DefaultController::articleUpdate

articleFormDisplay:
    path: /articleFormDisplay
    controller: App\Controller\DefaultController::articleFormDisplay

#deleteAuthorImage:
#    path: /adminDeleteAuthorImage
#    controller : App\Controller\DefaultController::deleteAuthorImage